b'import sys'
b'script, encoding, error = sys.argv'
b''
b''
b'def main(language_file, encoding, errors):'
b'line = language_file.readline()'
b''
b'if line:'
b'print_line(line, encoding, errors)'
b'return main(language_file, encoding, errors)'
b''
b''
b'def print_line(line, encoding, errors):'
b'next_lang = line.strip()'
b'raw_bytes = next_lang.encode(encoding, errors = errors)'
b'cooked_string = raw_bytes.decode(encoding, errors = errors)'
b''
b'print(raw_bytes, "<===>", cooked_string)'
b''
b''
b'languages = open("languages.txt", encoding = "utf-8")'
b''
b'main(languages, encoding, error)'
b''
b'languages.close()'
